# Generated by Django 5.0.2 on 2024-03-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=30)),
                ('order_number', models.PositiveIntegerField()),
                ('order_status', models.CharField(max_length=30)),
                ('total_item', models.PositiveIntegerField()),
                ('payment_method', models.CharField(max_length=30)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=100)),
                ('star', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=130)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
